### ISSUE TITLE
Azure/AzureOAuth2.ps1

### ISSUE THREAD

**Issue by manoharanP** [cmwky/powershell-os#1]
Hi Mr. Charles,

Good Day!

I have gone through your script and it looks intresting . I tried to execute on my own. But I am not able to get the output. 

I am getting below error. Could you please guide me to find out the issue?

Get-AzureBearerToken : A parameter cannot be found that matches parameter name 'bearerToken'.
At line:1 char:43
+ $token, $expiresOn = Get-AzureBearerToken @variables
+                                           ~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-AzureBearerToken], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Get-AzureBearerToken

**Comment by cmwky** [comment]
@manoharanP Absolutely, thanks for pointing this out. The `README` example was just incorrect for some reason. The proper use of `Get-AzureBearerToken` is 

```powershell
$token, $expiresOn = Get-AzureBearerToken -tenantId $variables["tenantId"] `
                                          -clientId $variables["clientId"] `
                                          -clientSecret $variables["clientSecret"] `
                                          -resource $variables["resource"]

$variables["bearerToken"] = $token
$variables["bearerTokenExpiresOn"] = $expiresOn
```

and the `bearerToken` can be accessed using `$variables["bearerToken"]`.

Thanks again for opening this Issue.. closing now as Resolved.
